### ISSUE TITLE
Attachment header error

### ISSUE THREAD

**Issue by chanhpng** [afterlogic/webmail-lite-8#1]
I use MS Exchange to store email and attachments. However, when downloading attachments, it will not open. I check that the header has 3 bytes redundant as follows:
"EF BB BF"
[header.zip](https://github.com/afterlogic/webmail-lite-8/files/1143863/header.zip)
Please help me fix it! Many thanks!

**Comment by vasil-sokolov** [comment]
Hello, 
these 3 bytes are BOM (Byte Order Mark). They appear in web server response if they are present in php file that's being called. In case of download any of mail attachments it is index.php. But in index.php stored in WebMail Lite 8 product's repository as well as in .zip archive we distribute, there is no BOM.

Did you make any changes in this file? Can you post here index.php from you installation?

**Comment by chanhpng** [comment]
Thanks vasil-sokolov! I has check sources in my server and fix it.
