### ISSUE TITLE
ALT_GR hijacking

### ISSUE THREAD

**Issue by oktayaa** [afterlogic/webmail-lite-8#10]
Hello. I appreciate that there are keyboard shortcuts for Italic, Bold, Underline etc, but can you make these configurable. I would like to be able to turn them off per user. Or at least change to a different combination.

A lot of international keyboard users utilize the ALT_GR (Right Alt) key to type complex characters. For instance on my setup I use ALT_GR + u to produce ü, except I can't do that with Afterlogic.

I haven't checked the source, the issue with Afterlogic might be with CTRL instead of ALT_GR but unfortunately it amounts to the same thing since ALT_GR is passed as CTRL by the OS. I believe this is standard.

I do have a userscript to disable hijacking on the client side but it is not ideal.

Thanks.

**Comment by afterlogic-support** [comment]
Thank you for your feedback, I have forwarded it to the developers for consideration.

**Comment by oktayaa** [comment]
Any updates?

**Comment by afterlogic-support** [comment]
I don't think there were any changes on this aspect. You're welcome to suggest any changes to the code, or post a feature request at https://afterlogic.uservoice.com - if a feature gets substantial amount of votes, we'll consider adding that.
