### ISSUE TITLE
Javascript Error on the login screen

### ISSUE THREAD

**Issue by thewebthingllc** [afterlogic/webmail-lite-8#100]
When I load the login screen I get these messages:

An error occurred while loading the component:
Error: Unable to process binding "template: function(){return { name:'CoreWebclient_InformationView'} }"
Message: Cannot find template with ID CoreWebclient_InformationView

The admin screens are working fine.

Version:
Name: Afterlogic WebMail Lite PHP
Version: 9.3.0.build7-build-a3

Linux Kernel:
3.2.63-grsec

The error first appears about a week ago. Until then we have had no problems. No new software was added and no configuration changes were made.

**Comment by afterlogic-support** [comment]
The error message indicates the following file is missing or cannot be read for some reason: `modules/CoreWebclient/templates/InformationView.html`
Check if the file is in place. Also, you may wish to [upgrade to the latest version](https://afterlogic.com/docs/webmail-lite/installation/upgrading-instructions).
