### ISSUE TITLE
incorrect username or password

### ISSUE THREAD

**Issue by sodared** [afterlogic/webmail-lite-8#101]
Hello，
I checked the /data/settings/config file, and the username is "superadmin" , the password is "" . However, I type the username and password in localhost/webmail/adminpanel/ , it is incorrect, any idea the reason of this issue ? or how can I troubleshoot the issue？

**Comment by afterlogic-support** [comment]
Make sure you're checking `data/settings/config.json` file, my guess is you might be looking at its backup copy `config.json.bak`.

**Comment by sodared** [comment]
sry, I tried to set the /data recursively writeable , and it works. So it may be the permission issue , thank you!
