### ISSUE TITLE
webmail wrong username and password

### ISSUE THREAD

**Issue by sodared** [afterlogic/webmail-lite-8#102]
hello, I used hMailServer + webmail 9.7, when I tried to login to webmail , there is an error 'The username or password you entered is incorrect.' , and here is part of logs in /hMailServer/webmail/data/logs , could you plz help me.

[08:38:35.38][0fc8b533] [POST(4)][ip:10.1.53.174] /webmail/?/Api/
[08:38:35.38][0fc8b533] POST > [Module, Method, Parameters, TenantName]
[08:38:35.38][0fc8b533]
[08:38:35.38][0fc8b533] Exception: Aurora\System\Exceptions\ApiException: ApiException in C:\hMailServer\webmail\modules\Core\Module.php:2051
Stack trace:
#0 [internal function]: Aurora\Modules\Core\Module->SetAuthDataAndGetAuthToken(false, '', false)
#1 C:\hMailServer\webmail\system\Module\AbstractModule.php(812): call_user_func_array(Array, Array)
#2 C:\hMailServer\webmail\system\Module\Decorator.php(54): Aurora\System\Module\AbstractModule->CallMethod('SetAuthDataAndG...', Array)
#3 C:\hMailServer\webmail\modules\Core\Module.php(2131): Aurora\System\Module\Decorator->__call('SetAuthDataAndG...', Array)
#4 [internal function]: Aurora\Modules\Core\Module->Login('sb.smec-cn.com', '', '', false)
#5 C:\hMailServer\webmail\system\Module\AbstractModule.php(812): call_user_func_array(Array, Array)
#6 C:\hMailServer\webmail\system\Module\Decorator.php(54): Aurora\System\Module\AbstractModule->CallMethod('Login', Array)
#7 C:\hMailServer\webmail\modules\StandardLoginFormWebclient\Module.php(47): Aurora\System\Module\Decorator->__call('Login', Array)
#8 [internal function]: Aurora\Modules\StandardLoginFormWebclient\Module->Login('sb.smec-cn.com', '', '', false)
#9 C:\hMailServer\webmail\system\Module\AbstractModule.php(812): call_user_func_array(Array, Array)
#10 C:\hMailServer\webmail\modules\Core\Module.php(626): Aurora\System\Module\AbstractModule->CallMethod('Login', Array, true)
#11 [internal function]: Aurora\Modules\Core\Module->EntryApi()
#12 C:\hMailServer\webmail\system\Router.php(105): call_user_func_array(Array, Array)
#13 C:\hMailServer\webmail\system\Module\Manager.php(604): Aurora\System\Router->route('api')
#14 C:\hMailServer\webmail\system\Application.php(132): Aurora\System\Module\Manager->RunEntry('api')
#15 C:\hMailServer\webmail\system\Application.php(102): Aurora\System\Application->Route('api')
#16 C:\hMailServer\webmail\index.php(21): Aurora\System\Application::Start()
#17 {main}, Code: 102, Message: ApiException

**Comment by afterlogic-support** [comment]
Make sure you have a mail server created in adminpanel, with IP/hostname of mailserver installation. Such error usually indicates there's no matching mail server record found. If you only have one mail server there, make sure its domains list is empty.

**Comment by sodared** [comment]
Thanks! @afterlogic-support  I just find out the reason:
I used hMailServer on localhost, the hMailServer has a feature called 'Auto-ban' , which means you'll not be allowed to login server  after 3 failures . So I failed at password for 3 times , the Auto-ban banned the  IP  127.0.0.1 , so that none of my domain account could access.
