### ISSUE TITLE
Install step 2 composer

### ISSUE THREAD

**Issue by piratov** [afterlogic/webmail-lite-8#104]
last composer ver.
OS win 10
php8.0.30

```
composer/installers contains a Composer plugin which is currently not in your allow-plugins config. See https://getcomposer.org/allow-plugins
Do you trust "composer/installers" to execute code and wish to enable it now? (writes "allow-plugins" to composer.json) [y,n,d,?] y
oomphinc/composer-installers-extender contains a Composer plugin which is currently not in your allow-plugins config. See https://getcomposer.org/allow-plugins
Do you trust "oomphinc/composer-installers-extender" to execute code and wish to enable it now? (writes "allow-plugins" to composer.json) [y,n,d,?] y
Installing dependencies from lock file (including require-dev)
Verifying lock file contents can be installed on current platform.
Nothing to install, update or remove
Package gufy/cpanel-php is abandoned, you should avoid using it. No replacement was suggested.
Generating autoload files
7 packages you are using are looking for funding.
Use the `composer fund` command to find out more!
> [ -d data ] || mkdir data
'[' is not recognized as an internal or external command,
operable program or batch file.
A subdirectory or file data already exists.
Script [ -d data ] || mkdir data handling the pre-config event returned with error code 1
Script @pre-config was called via post-install-cmd
```

**Comment by afterlogic-support** [comment]
Do you have Git installed? If so, the first thing I'd recommend is to use `git bash` instead of Windows standard command prompt. Right-click in the folder where you have the repository downloaded/cloned to, and select "Git Bash Here". You can also run it directly, the executable is found at `C:\Program Files\Git\git-bash.exe` by default, make sure to `cd` to correct directory after.

While this is mainly used on Linux systems, Windows users should have no issues running the scripts with `git bash` used.

**Comment by piratov** [comment]
Tried different ways with Git and failed to pass stage 2

Now I'm trying to install by downloading from here https://afterlogic.org/download/webmail-lite-php

But I don’t understand the description https://afterlogic.com/docs/webmail-lite/installation/compatibility-test
I click NEXT and get the message **Something went wrong. Adminpanel cannot be loaded.** (adminpanel/#/app-not-loaded)

![image](https://github.com/afterlogic/webmail-lite-8/assets/17856390/f45ce820-1228-494c-9320-10e4d898f0e1)

**Comment by afterlogic-support** [comment]
Check if you have any errors in PHP or webserver log files.

**Comment by piratov** [comment]
> Check if you have any errors in PHP or webserver log files.

No error

My error settings PHP

log_errors = On
display_errors = On
display_startup_errors = On
error_reporting = E_ALL & ~E_NOTICE & ~E_DEPRECATED & ~E_STRICT
error_log = 0_errors.log

**Comment by afterlogic-support** [comment]
There's a good chance that WebMail logs will help, then. In `data/settings/config.json` file, set "EnableLogging" to **true**:

```json
"EnableLogging": [
	true,
	"bool",
	null,
	"Activates debug logging"
],
```

then reproduce the issue and check the logs. In case if you're getting database-related error, configure database access by supplying "DBName", "DBLogin" and "DBPassword" values in the same file. You can also create database tables by running the following command:

```
php system/bin/console migrate
```

and see if that works.

**Comment by afterlogic-support** [comment]
For IIS, configuration guidelines are available as well; you can also move data directory out of web space, both the solutions are available at:

[Protecting data directory](https://afterlogic.com/docs/aurora-files/security/protecting-data-directory)

Hope this helps.

**Comment by piratov** [comment]
> For IIS, configuration guidelines are available as well; you can also move data directory out of web space, both the solutions are available at:
> 
> [Protecting data directory](https://afterlogic.com/docs/webmail-lite/security/protecting-data-directory)
> 
> Hope this helps.

thanks, I'll study it

**Comment by piratov** [comment]
more errors
[error-log-2023-10-10 _.txt](https://github.com/afterlogic/webmail-lite-8/files/12857997/error-log-2023-10-10._.txt)

I installed the settings from the mail and it was not possible to log in as the user.
![image](https://github.com/afterlogic/webmail-lite-8/assets/17856390/3e5ee4ba-2f77-4e20-8d06-36cab1de43ed)


It’s interesting that in the version https://github.com/afterlogic/webmail-lite with the same settings it works and installs perfectly.

**Comment by afterlogic-support** [comment]
Was the issue with adminpanel resolved, or are you still having problems accessing it?

With regard to error when accessing email account, the first thing to recheck is that you have a mail server added in admin interface, make sure it has an empty list in Domains area, and that IMAP/SMTP settings are valid. Also, make sure you have Logging verbosity level set to Debug, as the logs currently only hold errors and don't contain anything that resembles communication between WebMail and IMAP server. One common mistake I should also mention is attempting to log into an email account while still using /adminpanel/ URL.

**Comment by piratov** [comment]
> Was the issue with adminpanel resolved, or are you still having problems accessing it?
> 
Yes thank you

> With regard to error when accessing email account, the first thing to recheck is that you have a mail server added in admin interface, make sure it has an empty list in Domains area, and that IMAP/SMTP settings are valid. Also, make sure you have Logging verbosity level set to Debug, as the logs currently only hold errors and don't contain anything that resembles communication between WebMail and IMAP server. One common mistake I should also mention is attempting to log into an email account while still using /adminpanel/ URL.
>
Of course, the server is working and, as I wrote above in the earlier version, everything works great. As you noticed, the script doesn’t even make an attempt to connect to the IMAP server.

**Comment by afterlogic-support** [comment]
Can you share a screenshot of Mail Servers tab of adminpanel? I would assume you have a server added there, I need to see what it looks like.

**Comment by piratov** [comment]
Everything works in email clients. And tried your version here, it also works, but it’s for PHP7 (https://github.com/afterlogic/webmail-lite)
![image](https://github.com/afterlogic/webmail-lite-8/assets/17856390/babc2f26-40f0-4604-a8ae-6393ee7a3c7b)

**Comment by afterlogic-support** [comment]
This is really strange. Would you be able to share the installation URL as well as adminpanel credentials?
Please open a ticket at [our HelpDesk](https://s.afterlogic.com/helpdesk/) - it would help if you also provide any email account we could log in with.
While we don't offer guaranteed free support for WebMail Lite, this issue looks like something we're interested in getting to the bottom of.

**Comment by piratov** [comment]
>  HelpDesk and adminpanel 

![image](https://github.com/afterlogic/webmail-lite-8/assets/17856390/5a6763d7-dc9a-4867-b25b-863ea9f0fa9a)

**Comment by afterlogic-support** [comment]
Thanks. It seems there was an issue of some kind with creating database tables or updating configuration files. We've run  "Create/Update tables" and "Update configuration" in Database Settings screen of admin area and were able to log into the account.
