### ISSUE TITLE
Mail settings SMTP Server [question]

### ISSUE THREAD

**Issue by piratov** [afterlogic/webmail-lite-8#105]
In the SMTP Server settings there is a choice:
**No authentication**
**Use incoming mail's login/password of the user**
What is the difference between these two parameters? Tell me who knows or where to look information.

![image](https://github.com/afterlogic/webmail-lite-8/assets/17856390/dfb62892-7adb-4423-97f6-761f7b01e14b)

**Comment by afterlogic-support** [comment]
Have just answered this at: https://s.afterlogic.com/forum/forum_posts.asp?TID=8335&PN=1&TPN=1
