### ISSUE TITLE
Add setting configuring when an email will be marked as read

### ISSUE THREAD

**Issue by ifokkema** [afterlogic/webmail-lite-8#107]
Hi,

My new hosting provider is using your webmail, and I'm surprised how fast it works. I would like to configure, however, when an email will be marked as read. It's a common setting in many mail readers, often with options like "immediately", "after 5 seconds", "after 10 seconds", or "never". I always have it set it to "never". Now, I end up frequently marking emails as unread because the webmail is marking them as read immediately when I click on them just to get an idea of their contents.

Can such an option be added? Thanks!

**Comment by afterlogic-support** [comment]
Please feel free to post a feature request at: https://afterlogic.uservoice.com/forums/932335-webmail-pro

We use that resource when developing product's roadmap, so if the feature gets a good number of votes, there's a better chance of it getting implemented.
