### ISSUE TITLE
Failed to connect - database setting

### ISSUE THREAD

**Issue by vianmora** [afterlogic/webmail-lite-8#108]
Hello :) 
I've installed afterlogic on my webserver, but it seem i'm not able to configure Database settings, 
Normaly, i should hav a place where to put the Port, but i don't know where to fill it :/ 

![image](https://github.com/afterlogic/webmail-lite-8/assets/34892879/99ed2edb-cbb8-4d65-b52a-ad78c1dcf78f)

Is someone could help me plase ? :p 

---

**config :**  

Afterlogic WebMail Lite PHP
9.7.5.build12-build-o3

**Comment by afterlogic-support** [comment]
If you need to specify a non-standard SQL port, supply it in the host field using **hostname:port** syntax.

**Comment by afterlogic-support** [comment]
Oh, it looks like the issue isn't about connecting to the server, but about being unable to authenticate with login/password specified. Make sure to doublecheck the credentials supplied there.
