### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by shree0** [afterlogic/webmail-lite-8#11]
Can you please help how to install AfterLogic WebMail Lite 8.1.6 version in linux(Ubuntu 16.04)?

**Comment by afterlogic-support** [comment]
You can use the generic package and install it as described at the [Installation Instructions](https://afterlogic.com/docs/webmail-lite-8/installation/installation-instructions). Also, we've just updated [Debian/Ubuntu package for WebMail Lite 8](https://afterlogic.com/docs/webmail-lite-8/installation/installing-on-debian-ubuntu-linux).
