### ISSUE TITLE
Unable to use or find anything

### ISSUE THREAD

**Issue by R1NLER** [afterlogic/webmail-lite-8#110]
I have this error, it only happens on some accounts, and I would like to rule out that it's an issue with the webmail. With Outlook, it allows me to function correctly, but in this way, I can't access to search emails (it's used as an email archive).

> strtolower(): Passing null to parameter #1 ($string) of type string is deprecated in public_html\\oldmail\\vendor\\afterlogic\\mailso\\lib\\MailSo\\Base\\Utils.php on line 174

This one is open, but it seems a solution has been provided. I haven't tested it yet.

and 

> strlen(): Passing null to parameter #1 ($string) of type string is deprecated in public_html\\oldmail\\vendor\\afterlogic\\mailso\\lib\\MailSo\\Imap\\BodyStructure.php on line 372

![Captura de pantalla 2024-04-22 105946](https://github.com/afterlogic/webmail-lite-8/assets/90422888/f4f1d032-c1be-45cd-ab5f-84e19f3effbd)

**Comment by afterlogic-support** [comment]
Try adjusting error_reporting value of your PHP configuration so that non-critical messages are suppressed, for example:

```
error_reporting = E_ALL & ~E_DEPRECATED & ~E_STRICT
```

Also, you may wish to set display_errors to Off, that way the errors are only logged but aren't displayed in the browser, which is what causes the "Data transfer has failed" message to begin with.

**Comment by R1NLER** [comment]
I've checked the browser console and I'm receiving these two errors.


![Captura de pantalla 2024-04-22 124015](https://github.com/afterlogic/webmail-lite-8/assets/90422888/2bd3868d-7ad2-4afa-9936-2945705e40cf)

This one refers to this line:

>                                 s.setup && !1 !== s.setup.call(e, n, u, p) || e.addEventListener && e.addEventListener(O, p)),




![Captura de pantalla 2024-04-22 124057](https://github.com/afterlogic/webmail-lite-8/assets/90422888/b375c1ae-74af-4329-b851-5b1196a6dffe)

This other one refers to this.

![Captura de pantalla 2024-04-22 124111](https://github.com/afterlogic/webmail-lite-8/assets/90422888/fdbed9bb-b726-4bb8-a290-8f4fb2600583)

**Comment by afterlogic-support** [comment]
Well those message don't seem to be related to the error you've initially reported, they're more of suggestions on the code improvements.
