### ISSUE TITLE
Plugin/way for file based email-to-username lookups/authentication

### ISSUE THREAD

**Issue by v20z** [afterlogic/webmail-lite-8#112]
Hello Gentlemen.

Please advise plugin or way to perform username based login time authentication using email-to-username lookups, primarily against postfix virtuser file (one or several). And then a popup window for completing registration with a request for full name, email address to create main identity. Some ability to change the password for such logged users.

Thank You.

**Comment by afterlogic-support** [comment]
There's no such module for our product. If you wish to request custom development, please contact us at:
https://s.afterlogic.com/helpdesk/

Thank you.
