### ISSUE TITLE
There is no option to select a different address book when importing contacts.

### ISSUE THREAD

**Issue by lvarnava** [afterlogic/webmail-lite-8#117]
Debian GNU/Linux 12 (bookworm)
PHP 8.2.24
apache2 2.4.62
afterlogic-lite 9.8.0

Hi!
Set the mode for managing multiple address books.
Created a new address book.
Select it and import contacts from the vcf file.
But they are always imported to the default address book.
Is this a bug or a feature?
In some other web clients, there is an option to select a specific address book when importing.

**Comment by afterlogic-support** [comment]
Have just tested it using WebMail Lite [Live Demo](https://lite.afterlogic.com/), created an additional address book, selected it on Contacts screen and ran Import - the contacts were imported into the address book I have selected.

**Comment by lvarnava** [comment]
Unfortunately, I was unable to import the contact into another address book either here: https://webmail.afterlogic.com/ or there: https://lite.afterlogic.com/.

**Comment by lvarnava** [comment]
There is a problem on my server, I can't move a contact from one address book to another using drag and drop.
It works in the demo version.

**Comment by afterlogic-support** [comment]
See if you get any errors in the logs. Also, reproducing the issue on the blank install is worth a try. If you find a reliable way to reproduce such an issue on a fresh installation, let us know.

**Comment by lvarnava** [comment]
Thanks for the reply. Debug mode is on but the error log is empty. I'll try on a fresh installation.

**Comment by lvarnava** [comment]
> Debian GNU/Linux 12 (bookworm) PHP 8.2.24 apache2 2.4.62 afterlogic-lite 9.8.0
> 
> Hi! Set the mode for managing multiple address books. Created a new address book. Select it and import contacts from the vcf file. But they are always imported to the default address book. Is this a bug or a feature? In some other web clients, there is an option to select a specific address book when importing.

I wanted to clarify that import via drag and drop fails in my case. Import via the "import" button is successful.

**Comment by afterlogic-support** [comment]
Oh I see, I was indeed able to reproduce such an issue. Have reported it to the developers. Thanks!

**Comment by afterlogic-support** [comment]
Just wanted to let you know that the developers have corrected the issue, the fix will be included into the next update expected early next year. Thanks again - and Happy Holidays!
