### ISSUE TITLE
Issues reported by my users

### ISSUE THREAD

**Issue by oktayaa** [afterlogic/webmail-lite-8#12]
Some of my users are having the following issues with the latest version. (It was fine in the earlier releases)

* Signatures are not displayed, even though it is turned on in the settings

* When hitting Reply All either a blank message window comes up, or a message comes up but it is not the correct one, it's the previously displayed message

* When hitting forward, a blank message window comes up.

**Comment by afterlogic-support** [comment]
Are you getting the same issues on WebMail Lite Demo at https://lite.afterlogic.com/ ?

Also, regarding signatures - were you checking in Email Accounts screen, under Identity of email accounts?

**Comment by oktayaa** [comment]
Regarding Reply and Forward, I had some time to debug the issue. Below is the error message that is being generated.

[Wed Apr 11 16:15:26.316198 2018] [:error] [pid 22637] [client XXXXXX:32611] 
PHP Fatal error:  Uncaught exception 'Aurora\\System\\Exceptions\\ApiException' with message 'ApiException' in /opt/afterlogic-8.1.9/system/Api.php:1244\nStack trace:\n#0 /opt/afterlogic-8.1.9/modules/Mail/Module.php(5542): Aurora\\System\\Api::checkUserRoleIsAtLeast(2)\n#1 [internal function]: Aurora\\Modules\\Mail\\Module->EntryDownloadAttachment()\n#2 /opt/afterlogic-8.1.9/system/Module/AbstractModule.php(620): call_user_func_array(Array, Array)\n#3 /opt/afterlogic-8.1.9/system/Module/Manager.php(689): Aurora\\System\\Module\\AbstractModule->RunEntry('mail-attachment')\n#4 /opt/afterlogic-8.1.9/system/Application.php(88): Aurora\\System\\Module\\Manager->RunEntry('mail-attachment')\n#5 /opt/afterlogic-8.1.9/index.php(21): Aurora\\System\\Application::Start()\n#6 {main}\n  thrown in /opt/afterlogic-8.1.9/system/Api.php on line 1244, referer: https://XXXX.com/mail/

**Comment by afterlogic-support** [comment]
That looks like an older version, and there's a good chance the issue is fixed already. Can you try installing the latest 8.1.11 from https://afterlogic.org/download/webmail_php.zip and confirm whether those issues persist? No need to remove existing installation, you can install another one next to it.

**Comment by oktayaa** [comment]
I believe we are on 8.1.9. I will try .11 . Please close this. I will reopen if it doesn't fix the issue. Thanks for your support.
