### ISSUE TITLE
Error displaying text

### ISSUE THREAD

**Issue by lord-potato** [afterlogic/webmail-lite-8#15]
button function is displayed instead of button text, for example: COREWEBCLIENT/ACTION_SIGN_IN is displayed instead of Sign in, and everything in the admin panel is like that:
![image](https://user-images.githubusercontent.com/8261894/40310496-5288f102-5d0d-11e8-9d60-439d112a34c4.png)

**Comment by afterlogic-support** [comment]
Make sure data/ directory is writeable by web server, and try clearing everything under data/cache/ directory. 
Does it help?

**Comment by raisor1011** [comment]
No, still the same. Just for the test's sake, I chmodded the whole /var/www/html directory (with -R of course) 777, so there should be no access error. It's also being owned by www-data.
I deleted everything in cache, that didn't help either.

**Comment by afterlogic-support** [comment]
OK what if you try to click OK button on any of the screens?

**Comment by afterlogic-support** [comment]
Also, try changing CacheLangs setting in data/settings/config.json file and see if it helps.

**Comment by raisor1011** [comment]
Neither helped, it's still the same.

**Comment by afterlogic-support** [comment]
Hmm, is it possible to provide us with installation URL, and admin credentials?
Please use [our helpdesk](https://s.afterlogic.com/helpdesk/) to provide those privately. Thanks.

**Comment by raisor1011** [comment]
I did.

**Comment by afterlogic-support** [comment]
Developers have checked this, and looks like a server-side failure of some kind occurs there. Please check webserver/PHP logs and see if anything relevant there. Thank you.

**Comment by raphaelrpais** [comment]
@lord-potato , did you managed to fix the problem? I am stucked with the same issue here...
