### ISSUE TITLE
Login Form not showing just background 

### ISSUE THREAD

**Issue by rahulsav** [afterlogic/webmail-lite-8#16]
Hi,

I have version 8.1.11 webmail lite installed from cpanel on the domain http://email.sbscindia.com. It was working few days back. now login form is missing and only background is showing.

Regards,
Rahul

**Comment by mark-unionmarketing** [comment]
I am having the same issue after gulp js:min, I'm getting the error **Uncaught TypeError: t.getUserRole is not a function at Object.initTimezone (app.min.js?81122:29)** @ app.min.js?81122:29

**Comment by afterlogic-support** [comment]
Are you saying it worked correctly before running **gulp js:min**? Were the product originally installed from Github or from the [ZIP package](https://afterlogic.org/download/webmail-lite-php)?

**Comment by mark-unionmarketing** [comment]
I found out that reverting **moment-timezone** to **0.5.16** will fix the issue.

**Comment by afterlogic-support** [comment]
Thanks for the update, developers are notified, meantime this information might help other users.

**Comment by cialtronale** [comment]
Same problem for 8.1.12 in Firefox.
In app.js:1488 exception not catched for invalid query string:
`div.querySelectorAll("*,:x");`
I fixed it with try-catch:
```
try {   
       div.querySelectorAll("*,:x");
       rbuggyQSA.push(",.*:");
} catch (e) {}
```

**Comment by afterlogic-support** [comment]
Thank you. We'll be releasing version 8.2 of WebMail Lite in about a week, and the issue is not reproduced there, thus we hope the new update fixes the issue.
