### ISSUE TITLE
Login API

### ISSUE THREAD

**Issue by bishu** [afterlogic/webmail-lite-8#19]
Unable to find the
libraries/afterlogic/api.php

how can I use the Login API to login the webmail from my PHP website.

**Comment by afterlogic-support** [comment]
In case of current version 8 of WebMail Lite, please use the following guidelines:
https://afterlogic.com/docs/webmail-lite-8/developers-guide/logging-in-programmatically

**Comment by bishu** [comment]
Oh! That's great ! It is working find.
How can we change the Logout URL 
Means when my client click on the logout I want it to redirect to my homepage.

**Comment by afterlogic-support** [comment]
You can set it in data/settings/modules/CoreWebclient.config.json file, CustomLogoutUrl parameter.
