### ISSUE TITLE
Can't login superadmin

### ISSUE THREAD

**Issue by mynpt** [afterlogic/webmail-lite-8#2]
I has downloaded source from https://afterlogic.org/webmail-lite-8
I can't login as superadmin with blank password. Please help me check it, thanks!

**Comment by afterlogic-support** [comment]
Make sure data/ directory of the installation is recursively writeable by webserver. Let us know if that has helped.

**Comment by mynpt** [comment]
I has set chmod and chown for data/ directory.
![capture](https://user-images.githubusercontent.com/22538787/28205220-42404dec-68ab-11e7-85c9-31dbc4a76e5d.png)
But it not work.

**Comment by afterlogic-support** [comment]
Please check if you have data/settings/config.json file in place, and that AdminPassword is indeed set to empty string as follows:

    "AdminPassword": [
        "",
        "string"
    ],

If it actually has some value there, set it to empty string and try logging in.

**Comment by mynpt** [comment]
Here is my config file in data/settings:
[config.json.txt](https://github.com/afterlogic/webmail-lite-8/files/1147864/config.json.txt)

**Comment by afterlogic-support** [comment]
Ok, thank you.
Are you getting any errors when trying to login? Or you're simply redirected back to login page?
Also, if you check cookies in the browser console (F12 in Google Chrome, Application tab) - do you see AuthToken cookie there?

**Comment by mynpt** [comment]
Login failed with "The username or password you entered is incorrect." message in the login page.
I can't found AuthToken cookie:
![untitled](https://user-images.githubusercontent.com/22538787/28207054-78103584-68b2-11e7-8d40-7154a1a48d46.png)

**Comment by mynpt** [comment]
This is log file:
[log-2017-07-14.txt](https://github.com/afterlogic/webmail-lite-8/files/1147991/log-2017-07-14.txt)

**Comment by vasil-sokolov** [comment]
Hello,
For some reason admin authentication logic can't check password. It seems crypt() method didn't work correctly. We need more debug info. Please replace modules/AdminAuth/Module.php file with this one. 
[Module.php.zip](https://github.com/afterlogic/webmail-lite-8/files/1148464/Module.php.zip)
Then clear logs and do login roundtrip.

Also please specify version of php you are using.

Will not be superfluous, if you turn on displaying of error reports by adding lines below
ini_set('display_errors', 1);
ini_set('display_startup_errors', 1);
error_reporting(E_ALL);

to top of index.php

Then you will be able to see and tell us how server response looks with errors. ) 

We are interested in request with these parametes in it
Module "StandardLoginFormWebclient"
Method "Login"

**Comment by mynpt** [comment]
I use php version 5.4.25. This is logfile:
[log-2017-07-17.txt](https://github.com/afterlogic/webmail-lite-8/files/1151493/log-2017-07-17.txt)
In my case, I had to edit all empty() function as:
$bCorrectEmptyPass = empty($aArgs['Password']) && empty($oSettings->GetConf('AdminPassword'));
To:
$AdminPassword = $oSettings->GetConf('AdminPassword');
$bCorrectEmptyPass = empty($aArgs['Password']) && empty($AdminPassword);
____________
empty($oSettings->GetConf('AdminPassword')) is Fatal error: Can't use method return value in write context

**Comment by shree0** [comment]
Can you please help how to install AfterLogic WebMail Lite 8.1.6 version in linux?

**Comment by afterlogic-support** [comment]
In the current version 8.1.6 of the product, the issue is corrected.
