### ISSUE TITLE
Custom Code on the Header of the Webmail Lite

### ISSUE THREAD

**Issue by bishu** [afterlogic/webmail-lite-8#20]
I would like to enter a custom PHP Code on the header section which should be run on every page of the website.
I am very confuse where I have to write my custom code.

**Comment by afterlogic-support** [comment]
I'm sorry, not sure what you're trying to do. PHP code is not executed on the pages, it's done "behind the scenes" to affect HTML and JavaScript content viewed with web browser.

If you require assistance from our developers, that can be arranged in terms of Professional Services: https://afterlogic.works/

**Comment by bishu** [comment]
As my webmail lite is login using the Login In logging-in-programmatically
I don't want my webmail to be open directly if the user are not login in my parent website.
So I would like to check whether the user has login or not using the PHP Code as
```
<?php
include_once "../security.php"; //This is my security class for my parent website
if (!IsLoggedIn()) { // <-- check whether not logged in my parent website.
  // As the user is not login it will redirect to my parent website.
} 
?>
```
If the above code are fixed on all the page then the user will be redirected to my parent website if they are not login on the parent website.

**Comment by afterlogic-support** [comment]
Well there's a simpler way. In **data/settings/modules/StandardLoginFormWebclient.config.json** configuration file, set **CustomLoginUrl** to the address of the page users need to be redirected if they attempt to open WebMail login page directly.

**Comment by bishu** [comment]
Thanks you very much sir. 
It is working Perfect.

Is there anyway for pro-grammatically logout

**Comment by afterlogic-support** [comment]
You just need to delete or otherwise invalidate **AuthToken** cookie, that would effectively log the user out.

**Comment by neoget-dipankar** [comment]
Is there any logout script available?? so I can refer to it. AuthToken invalidation is not working for me and also sometime logout functionality is not working.

**Comment by afterlogic-support** [comment]
> Is there any logout script available?? so I can refer to it. AuthToken invalidation is not working for me and also sometime logout functionality is not working.

Have answered this at: https://github.com/afterlogic/webmail-lite-8/issues/78
