### ISSUE TITLE
CardDAV support for contact

### ISSUE THREAD

**Issue by erikhubers** [afterlogic/webmail-lite-8#21]
Hey there!

Amazing webmail client! Really love the look and feel. Would be even more amazing if CardDAV was supported for contact synchronization with an external CardDAV service instead of a one off import using CSV.

Kind regards,

Erik

**Comment by afterlogic-support** [comment]
Hello Erik,

There's complete CalDAV and CardDAV support in commercial edition, WebMail Pro:

https://afterlogic.com/webmail-client

It's available for full-featured 30-day trial so you can try it out and see if it meets your requirements.

--
Regards, Igor
Afterlogic Team

**Comment by erikhubers** [comment]
Thank you for the quick response time. I'd be delighted if this was implemented and be tempted to go for a Pro version in that case :)
