### ISSUE TITLE
Social buttons: font-size

### ISSUE THREAD

**Issue by denji** [afterlogic/webmail-lite-8#23]
Social buttons have problems with the maximum size when translating to another language

```diff
.login_panel .social .button .text {
+    font-size: 10.5pt;
    font-weight: normal;
}
```

![ui](https://user-images.githubusercontent.com/3759759/42886068-51849c40-8aab-11e8-9e27-66abee8e36a7.png)

**Comment by afterlogic-support** [comment]
Thank you, I've forwarded this to the developers, your suggestion will be considered of course.
