### ISSUE TITLE
Set default domain

### ISSUE THREAD

**Issue by kwade00** [afterlogic/webmail-lite-8#24]
In WebMail 6 it was possible to set a default domain name, so that users didn't need to type their full email address to login. They could just type the username part and the rest was automatically added. I can't find a way to do this in WebMail Lite 8. Am I missing it? I'm on 8.1.12.

**Comment by afterlogic-support** [comment]
That's not currently supported, we'll be re-adding this feature to v8 in the near future.

**Comment by kwade00** [comment]
Great! Is there an open issue for it that I can follow so I'll know when it's done?

**Comment by afterlogic-support** [comment]
Though in fact, let's reopen this issue so it stays open till the feature itself is there, then we'll post the update here and close the issue.

**Comment by merilturock** [comment]
Default domain is a much needed feature ..

**Comment by phaberest** [comment]
Is it something we can help to develop?

**Comment by afterlogic-support** [comment]
Hello,
I believe the feature in question is available already, please see:
[Configuring mail login form](https://afterlogic.com/docs/webmail-pro-8/configuring-webmail/configuring-mail-login-form)
Let us know if it works for you. Thanks.
