### ISSUE TITLE
OnlyPasswordForAccountCreate (wrong type)

### ISSUE THREAD

**Issue by navossoc** [afterlogic/webmail-lite-8#25]
I'm pretty sure the type should be `bool` and not `book`.

`webmail_php\modules\OAuthIntegratorWebclient\config.json`

```json
    "OnlyPasswordForAccountCreate": [
		true,
		"book"
	],
```

[]'s

**Comment by afterlogic-support** [comment]
Good point, thank you, we've corrected this.
