### ISSUE TITLE
Not working on mobile properly

### ISSUE THREAD

**Issue by worldofmadness** [afterlogic/webmail-lite-8#27]
the site isnt very mobile as you make it smaller it stops and does not go to phone size on login screen or for email
![chrome_2018-10-09_01-49-44](https://user-images.githubusercontent.com/17691564/46640742-a975b880-cb65-11e8-97c5-a94877d79849.png)
![chrome_2018-10-09_01-50-33](https://user-images.githubusercontent.com/17691564/46640762-c1e5d300-cb65-11e8-8a9b-e962dc1105d3.png)

**Comment by afterlogic-support** [comment]
Mobile version of the interface is only available in WebMail Pro:

https://afterlogic.com/webmail-client
