### ISSUE TITLE
Cannot load mail servers config from DB

### ISSUE THREAD

**Issue by garciacarmonaam** [afterlogic/webmail-lite-8#29]
Hello,

I am trying to add new mail servers to AfterLogic adding new rows to strings, texts, bool and int tables 

Anyway it is impossible to login with these domains then despite of being matched with the same id (I don't refer to primary key, but to the second param.

Are really those configs loaded from another place?

**Comment by afterlogic-support** [comment]
Sorry, not sure what exactly you're doing, do you need to add a mail server via API? And can you maybe provide a few lines of your code?

**Comment by garciacarmonaam** [comment]
Hello,

I just was making MySQL scripts with INSERT TO order through MySQLi.

I didn't know about your api. Far more easier. I'll work in.

Thanks. I'll keep you up-to-date.
