### ISSUE TITLE
Cookies are disabled in the browser. Please enable them for this web site and reload the page.

### ISSUE THREAD

**Issue by iReligion** [afterlogic/webmail-lite-8#33]
The popup "Cookies are disabled in the browser. Please enable them for this web site and reload the page." keeps displaying, even though I know for a fact that cookies are enabled on my browser. Usign Google Chrome, and Cookies are enabled in Advanced Settings > Content. 

https://i.imgur.com/frGGev5.png
The cookies are being created, but no value is being set to them. Once again, though, cookies work everywhere else except for Webmail Lite.

**Comment by iReligion** [comment]
Tested on other browsers, and on mobile, the issue persists. Definitely isn't an issue with my browser.

**Comment by afterlogic-support** [comment]
Hello,

Are you on 8.2.3 version?
https://afterlogic.com/docs/webmail-lite-8/troubleshooting/detecting-version-used

**Comment by afterlogic-support** [comment]
Would it be possible to get an installation URL so the developers could check it? If you'd rather not post that information here, you can send it to us privately [via HelpDesk](https://s.afterlogic.com/helpdesk/) or email us at support@afterlogic.com.

**Comment by iReligion** [comment]
https://landon.pw/mail/index.php

**Comment by ytteroy** [comment]
Hello, I have also faced this problem. This problem occurs only for a few users. Do you have any additional information to fix this error? I'm using Cloudflare.
