### ISSUE TITLE
In Safari mails text are invisible

### ISSUE THREAD

**Issue by ysilvela** [afterlogic/webmail-lite-8#34]
In Safari browser we cant see any mail. The list are filled but text are transparent and cant select any mail.

Thanks
<img width="724" alt="captura de pantalla 2018-11-24 a las 10 57 08" src="https://user-images.githubusercontent.com/6481036/48966746-b6485180-efd7-11e8-80bf-5aa68c7e1d35.png">

**Comment by ysilvela** [comment]
I only reproduce the issue in Safari and mac.

**Comment by afterlogic-support** [comment]
Understood, thank you, developers are notified.

**Comment by afterlogic-support** [comment]
Developers have confirmed and corrected the problem. The fix will be available in the next release of the product. Thanks again!
