### ISSUE TITLE
Undefined class constant 'TenantAdmin'

### ISSUE THREAD

**Issue by n00b42** [afterlogic/webmail-lite-8#35]
When trying to update a mail server, it does not change the settings.
The requests results in a 500 Internal Server Error.

Apache log shows the following associated error
 `[php7:error] PHP Fatal error: 
Uncaught Error: Undefined class constant 'TenantAdmin' in /var/www/vhosts/webmail/modules/Mail/Module.php:1274`

**Comment by afterlogic-support** [comment]
We've just released new version 8.2.4 with a number of issues fixed, including this one. 
Upgrading is recommended: https://afterlogic.com/docs/webmail-lite-8/installation/upgrading-instructions
