### ISSUE TITLE
error opening mail in cPanel installation

### ISSUE THREAD

**Issue by ysilvela** [afterlogic/webmail-lite-8#38]
I install webmail over WHM/cPanel.

If I enter to webmail-lite first from cPanel (without explicit authentication) webmail-lite request me the superadmin password.
Why webmail force always to enter using webmail.[domain] and not from cPanel?

**Comment by BhagyashreeKoyande** [comment]
Hello, I have installed after logic webmail 8 and run on server. I login admin panel vai superadmin and created database and gmail mail server but when I try to login vai gmail credentials it display incorrect username and password. Please help, I am attaching log file for reference.
[log-2020-08-07.txt](https://github.com/afterlogic/webmail-lite-8/files/5039260/log-2020-08-07.txt)

**Comment by afterlogic-support** [comment]
@BhagyashreeKoyande We've already answered this on forum, and the issue isn't related to cPanel anyway.
