### ISSUE TITLE
Fail to connect own mail server

### ISSUE THREAD

**Issue by pavel-gololobov** [afterlogic/webmail-lite-8#39]
I have installed my own mail server [as article](https://thomas-leister.de/en/mailserver-debian-stretch/). Desktop clients (like Thunderbird) works well, but Afterlogic webmail fails to connect server.

Log trace:

`[12:41:41.45][5e9ffc98] IMAP[NOTE]: Start connection to "ssl://mail.levap.ru:143"
[12:41:41.62][5e9ffc98] IMAP[NOTICE]: Socket: [2] stream_socket_client(): SSL operation failed with code 1. OpenSSL Error messages:
error:1408F10B:SSL routines:ssl3_get_record:wrong version number
[12:41:41.62][5e9ffc98] IMAP[NOTICE]: MailSo\Net\Exceptions\SocketCanNotConnectToHostException: Can't connect to host "ssl://mail.levap.ru:143" in /usr/share/afterlogic/vendor/afterlogic/mailso/lib/MailSo/Net/NetClient.php:283
Stack trace:
#0 /usr/share/afterlogic/vendor/afterlogic/mailso/lib/MailSo/Imap/ImapClient.php(149): MailSo\Net\NetClient->Connect('mail.levap.ru', 143, 1, false)
#1 /usr/share/afterlogic/modules/Mail/Managers/Main/Manager.php(106): MailSo\Imap\ImapClient->Connect('mail.levap.ru', 143, 1, false)
#2 /usr/share/afterlogic/modules/Mail/Managers/Main/Manager.php(181): Aurora\Modules\Mail\Managers\Main\Manager->_getImapClient(Object(Aurora\Modules\Mail\Classes\Account))
#3 /usr/share/afterlogic/modules/Mail/Module.php(678): Aurora\Modules\Mail\Managers\Main\Manager->validateAccountConnection(Object(Aurora\Modules\Mail\Classes\Account), false)
#4 [internal function]: Aurora\Modules\Mail\Module->CreateAccount(4, '', 'full mail address', 'full mail address', 'password', Array)
#5 /usr/share/afterlogic/system/Module/AbstractModule.php(847): call_user_func_array(Array, Array)
#6 /usr/share/afterlogic/system/Module/Decorator.php(51): Aurora\System\Module\AbstractModule->CallMethod('CreateAccount', Array)
#7 /usr/share/afterlogic/modules/Mail/Module.php(5355): Aurora\System\Module\Decorator->__call('CreateAccount', Array)
#8 /usr/share/afterlogic/system/EventEmitter.php(164): Aurora\Modules\Mail\Module->onLogin(Array, false, NULL)
#9 /usr/share/afterlogic/system/Module/Manager.php(688): Aurora\System\EventEmitter->emit('Core', 'Login', Array, false, Object(Closure))
#10 /usr/share/afterlogic/system/Module/AbstractModule.php(385): Aurora\System\Module\Manager->broadcastEvent('Core', 'Login', Array, false)
#11 /usr/share/afterlogic/modules/Core/Module.php(1845): Aurora\System\Module\AbstractModule->broadcastEvent('Login', Array, false)
#12 [internal function]: Aurora\Modules\Core\Module->Login('login', 'password', '', false)
#13 /usr/share/afterlogic/system/Module/AbstractModule.php(847): call_user_func_array(Array, Array)
#14 /usr/share/afterlogic/system/Module/Decorator.php(51): Aurora\System\Module\AbstractModule->CallMethod('Login', Array)
#15 /usr/share/afterlogic/modules/StandardLoginFormWebclient/Module.php(45): Aurora\System\Module\Decorator->__call('Login', Array)
#16 [internal function]: Aurora\Modules\StandardLoginFormWebclient\Module->Login('login', 'password', '', false)
#17 /usr/share/afterlogic/system/Module/AbstractModule.php(847): call_user_func_array(Array, Array)
#18 /usr/share/afterlogic/modules/Core/Module.php(590): Aurora\System\Module\AbstractModule->CallMethod('Login', Array, true)
#19 [internal function]: Aurora\Modules\Core\Module->EntryApi()
#20 /usr/share/afterlogic/system/Router.php(108): call_user_func_array(Array, Array)
#21 /usr/share/afterlogic/system/Module/Manager.php(566): Aurora\System\Router->route('api')
#22 /usr/share/afterlogic/system/Application.php(87): Aurora\System\Module\Manager->RunEntry('api')
#23 /usr/share/afterlogic/index.php(21): Aurora\System\Application::Start()
#24 {main}
[12:41:41.62][5e9ffc98] Can't connect to host "ssl://mail.levap.ru:143"
[12:41:41.62][5e9ffc98] INFO[MEMORY]: Memory peak usage: 2MB
[12:41:41.62][5e9ffc98] INFO[TIME]: Time delta: 1546087301.6285`

I can make an account for you to test.

**Comment by afterlogic-support** [comment]
Port 143 is typically used for non-SSL access, try connecting to it with SSL disabled, or use port 993 for SSL-enabled access.
