### ISSUE TITLE
Lack of clear discernment between versions

### ISSUE THREAD

**Issue by fragtion** [afterlogic/webmail-lite-8#4]
Despite trying to find an answer on the Afterlogic website, and viewing the github readme's, I can't seem to figure out why there are two distinct versions of webmail-lite (the normal one and the new 8 version). Yes I can see that the one is "newer", has more features, and requires Node.js etc to operate. But the existing version is still under active development too? There needs to be a comparison of features somewhere, or disclosure of reasons for why a user should choose the one version over the other. Right now the user is met with a fork in the road and needs to make a decision which version they want - both being actively developed... This is going to inhibit the number of new installations using this software. Why are there two independent versions, which should I use, and why? Is it worth using webmail-lite if webmail-lite-8 will eventually replace it completely? Or will they forever be two distinct, actively-developed products so that I can feel comfortable using either version? Some clarity please? ^_^..  Thank you..

**Comment by vasil-sokolov** [comment]
The new v8 will completely replace the current version soon. Currently WebMail Lite 8 is still in Beta status. We published it for getting some feedback from real users. The new version has some important differences as compared to the current stable version v7. It's modular (making plugins is much easier) and it has more flexible model of data storing in database.

So, if you want to use WebMail Lite in production you should choose the current stable version (https://afterlogic.org/webmail-lite). On the other hand if you're interested in trying the new product or helping us make it better, you can give WebMail Lite 8 at try: https://afterlogic.org/webmail-lite-8.

**Comment by fragtion** [comment]
Great information. I'm going to give WebMail Lite 8 a try, then, as it seems to be the way forward for the future! Thank you @vasil-sokolov
