### ISSUE TITLE
sent real ip to imap server

### ISSUE THREAD

**Issue by cmbilisim** [afterlogic/webmail-lite-8#40]
Remote IP address is not showing up correctly in mail logs

Here is mail log when I am connecting from web mail
`imap-login: Info: Login: user=<**********>, method=PLAIN, rip=127.0.0.1, lip=127.0.0.1, mpid=23945, secured`

Is it a way to record correctly the rip address instead of 127.0.0.1 into mail logs?

**Comment by afterlogic-support** [comment]
It's the real IP of the webmail client. If webmail client and mail server are installed on the same machine, then the mail server will see the webmail client's IP as 127.0.0.1. If you want to have another IP address displayed there, you need to install webmail on another host. Then your mail server will see that another IP address (the IP of the server where the webmail is now installed).

**Comment by cmbilisim** [comment]
I want to send IP address of the user (web server REMOTE_ADDR) to IMAP server.

Roundcube has a plugin for this. https://plugins.roundcube.net/packages/cor/dovecot-ident

Is there a plugin or a method in Afterlogic that I can use?

**Comment by afterlogic-support** [comment]
The closest option we have available is adding X-Originating-IP header with sender's IP address there. It's enabled by setting **XOriginatingIP** to **true** in **data/settings/Mail.config.json** file.

**Comment by cmbilisim** [comment]
XOriginatingIP only adds X-Originating-IP header information to sent mails. It does not send any information for IMAP connection.

**Comment by afterlogic-support** [comment]
That is correct.

Please note that WebMail Lite is a free open-source product, so please feel free to add the functionality you require. If you may be interested in custom development, please contact us at: https://s.afterlogic.com/helpdesk/
