### ISSUE TITLE
Auroa not autoloadble

### ISSUE THREAD

**Issue by gummipunkt** [afterlogic/webmail-lite-8#41]
gummipunkt@gummipunkt:/var/www/webmail$ php composer.phar run pre-config
> [ -d data ] || mkdir data
Class Aurora\Installer is not autoloadable, can not call pre-config script

**Comment by afterlogic-support** [comment]
We weren't able to reproduce it with the latest package. Make sure to [download the latest archive](https://github.com/afterlogic/webmail-lite-8/archive/latest.zip) and obtain the [latest composer build](https://getcomposer.org/composer.phar). If the issue persists with those, let us know what PHP version you use.

**Comment by gummipunkt** [comment]
Hi,

Thanks for your answer. I've downloaded it again and now it worked. But: After finish the installation process, I go to webmail.gummipunkt.eu

"No Internet connection"

It isn't possible to login with superadmin. Do you've any glue what the problem could be?+

Best,
Patrick

**Comment by afterlogic-support** [comment]
WebMail sends a request to https://webmail.gummipunkt.eu/?/Api/ address, and gets Error 500. That's a webserver-level error, you need to check webserver/PHP error logs to check what may be causing the issue.
