### ISSUE TITLE
Install new release in cPanel

### ISSUE THREAD

**Issue by souzadavi** [afterlogic/webmail-lite-8#43]
Hello, the docs: in https://afterlogic.com/docs/webmail-lite/installation/install-on-cpanel show how to install this webmail in cpanel server. But the version is 7. I would like to update the webmail in my server with newest release. Is it possible?

thanks

**Comment by afterlogic-support** [comment]
You're looking for [WebMail Lite v8 install on cPanel](https://afterlogic.com/docs/webmail-lite-8/installation/install-on-cpanel) instructions. Note that direct upgrade from v7 isn't supported, it needs to be removed first. [Data migration is available](url) though.
Also bear in mind that this kind of installation offers a limited feature set, you may wish to consider [installing from ZIP package](https://afterlogic.com/docs/webmail-lite-8/installation/install-on-cpanel-from-zip-package) instead.
