### ISSUE TITLE
show pgp encrypted mail inline

### ISSUE THREAD

**Issue by nextgen-networks** [afterlogic/webmail-lite-8#45]
present behavior:
encrypted mails are shown as blank messages with attachments that contain encrypted content.

expected behavior:
messages display encrypted content inline in message main body.
you are promted to enter the decryption password to decrypt message that is shown inline main body for whole session.

**Comment by afterlogic-support** [comment]
The developers have just checked this on [WebMail Live Demo](https://webmail.afterlogic.com/), and the behavior seems to match the expected one:
![openpgp-image](https://user-images.githubusercontent.com/16918936/57610836-35c3e000-757a-11e9-86f9-972c97a9282d.png)
Please check it on the live demo and let us know if it works as expected for you. Note that while it's WebMail Pro demo, it should work the same way for Lite, too.

**Comment by nextgen-networks** [comment]
Here are screenshots how messages got displayed in my case:
![2019-05-13 encrypted msg - Afterlogic WebMail lite 8 2 19-1](https://user-images.githubusercontent.com/21206978/57611653-a3204280-7573-11e9-9d9f-6d9ab7b89276.jpg)

Afterlogic itself is installed as web application via Plesk Onyx 17.8.11 Update #53
![2019-05-13 Afterlogic WebMail lite 8 2 19-1 Plesk 17 8 11 install](https://user-images.githubusercontent.com/21206978/57611654-a3204280-7573-11e9-92f8-64131a501ad6.jpg)

**Comment by afterlogic-support** [comment]
Can you post the message itself as EML file? You can forward it as attachment to [support@afterlogic.com](mailto:support@afterlogic.com) address, thanks.

**Comment by nextgen-networks** [comment]
Hmm - sorry the message contains very sensitive information i don't want to forward.
But i've written a test message to myself. Guess what? It was displayed correct!

So what was the difference? -> The the crypto application and the crypto properties of the message.

As wrapper around the encrypted message that could not displayed correct the content type was set to:

> Content-Type: multipart/encrypted;
>  protocol="application/pgp-encrypted";
>  boundary="BOUNDARY-ID"

Within the encrypted attachment of the encrypted message that could not displayed correct the content type was set to:
> Content-Type: multipart/mixed; boundary="BOUNDARY-ID";
>  protected-headers="v1"

The test message that could be displayed has content type setting as follows:
> Content-Type: text/plain; charset="utf-8"

To get a better understanding i've removed most privacy related data from the message that could not displayed correctly and paste it here as text:
> Return-Path: <SENDER@DOMAIN.TLD>
X-Spam-Checker-Version: SpamAssassin 3.4.1 (2015-04-28) on RECEIVER.HOST-DOMAIN.TLD
X-Spam-Level: 
X-Spam-Status: No, score=-2.9 required=6.0 tests=BAYES_00,ENCRYPTED_MESSAGE,
	RCVD_IN_DNSWL_NONE,TVD_SPACE_RATIO autolearn=ham autolearn_force=no
	version=3.4.1
X-Original-To: RECEIVER@DOMAIN.TLD
Delivered-To: RECEIVER@DOMAIN.TLD
Received: from SENDER.HOST-DOMAIN.TLD (SENDER.HOST-DOMAIN.TLD [SENDER.HOST-IP])
	by RECEIVER.HOST-DOMAIN.TLD (Postfix) with ESMTPS id POSTFIX-ID
	for <RECEIVER@DOMAIN.TLD>; RECEIVE-DATE
Authentication-Results: RECEIVER.HOST-DOMAIN.TLD;
	dkim=none header.i=SENDER@DOMAIN.TLD;
        spf=none (sender IP is SENDER.HOST-IP) smtp.mailfrom=SENDER@DOMAIN.TLD smtp.helo=SENDER.HOST-DOMAIN.TLD
Received-SPF: none (RECEIVER.HOST-DOMAIN.TLD: no valid SPF record)
Received: from [IP] ([IP]) by MAILRELAY.RECEIVER-DOMAIN.TLD
 (mreue006 [IP]) with ESMTPSA (Nemesis) id
 ID for <RECEIVER@DOMAIN.TLD>; DATE
 +DST
To: RECEIVER-NAME <RECEIVER@DOMAIN.TLD>
From: SENDER-NAME <SENDER@DOMAIN.TLD>
Openpgp: preference=signencrypt
Autocrypt: addr=SENDER@DOMAIN.TLD; prefer-encrypt=mutual; keydata=
 KEYDATA==
Message-ID: <ID@SENDER-DOMAIN.TLD>
Date: DATE
User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:52.0) Gecko/20100101
 Thunderbird/52.7.0
MIME-Version: 1.0
Subject: Encrypted Message
Content-Type: multipart/encrypted;
 protocol="application/pgp-encrypted";
 boundary="BOUNDARY-ID"
X-Provags-ID: X-PROVAGS-ID==
X-UI-Out-Filterresults: notjunk:ID=
X-Virus-Scanned: clamav-milter 0.99.4 at RECEIVER.HOST-DOMAIN.TLD
X-Virus-Status: Clean
>
> This is an OpenPGP/MIME encrypted message (RFC 4880 and 3156)
--BOUNDARY-ID
Content-Type: application/pgp-encrypted
Content-Description: PGP/MIME version identification
>
>Version: 1
>
>--BOUNDARY-ID
Content-Type: application/octet-stream; name="encrypted.asc"
Content-Description: OpenPGP encrypted message
Content-Disposition: inline; filename="encrypted.asc"
>
>-----BEGIN PGP MESSAGE-----
Version: GnuPG v2
>
>CRYPTED-MESSAGE==
=ID
-----END PGP MESSAGE-----
>
>--BOUNDARY-ID--

**Comment by afterlogic-support** [comment]
In current implementation of OpenPGP, only encrypted text/plain messages are supported, while in that message it's application/octet-stream.
