### ISSUE TITLE
Extremely Slow

### ISSUE THREAD

**Issue by paschaldev** [afterlogic/webmail-lite-8#46]
<img width="2556" alt="Screenshot 2019-07-26 at 11 19 24" src="https://user-images.githubusercontent.com/13323281/61945239-67ecb780-af97-11e9-9654-f0552a494d3b.png">

Using webmail lite has been difficult, it takes about 3minutes wait time for the login page to be rendered so users can login. 

The screenshot above was when the internet speed was at 17Mbps. The initial JS script that initiates other smaller items alone is about 1MB, this is too large especially here in Africa where internet speed is a challenge. Having to wait 3minutes before login is not ideal. Can dynamic JS loading and code splitting with Webpack be implemented?

Any help or suggestions on how this can be fine-tuned?

**Comment by afterlogic-support** [comment]
Are you using the latest 8.3.5 release? And do you encounter the same performance issue on [Live Demo](https://lite.afterlogic.com/)?

**Comment by paschaldev** [comment]
Yes, latest release. The live demo loads very fast. This is my installation link, check it out and see: http://ibstmedia.com/mail/

**Comment by afterlogic-support** [comment]
Thanks.

Just heard from the developers on this, they state there's currently no workaround for that. The primary file is rather complex and contains the core client-side code required for the product to function. As you can see from the console output, module-specific code is loaded separately.

The suggestion we currently have is to enable GZip compression on your web server level. Our test show that, if we limit speed to about 15Mbps, app.min.js file is loaded within 5-6 seconds - with GZip enabled, that is.

**Comment by paschaldev** [comment]
How do I enable G-ZIP compression?

**Comment by paschaldev** [comment]
Found it, enabled it. It loads within 50seconds now. Any more optimization tips?

**Comment by afterlogic-support** [comment]
That's the only idea we could think of at the moment.
