### ISSUE TITLE
Auto-provisioning of new users doesn't work for the mail login form.

### ISSUE THREAD

**Issue by pbsds** [afterlogic/webmail-lite-8#47]
I want to present a simple user login for my users, not having to type out the pesky domain.
I therefore switched over to using the "mail" login form instead of the "login" login form. But it seems the "mail" login form is unable to create new users automatically.

# My steps to reproduce:

* The "Allow auto-provisioning of new users" in the admin interface is checked.
* Only one mail server is configured with only a single domain.
* Set "DefaultAnonymScreenHash" in `CoreWebclient.config.json` to "mail".
* Set "Disabled" in `MailLoginFormWebclient.config.json` to `false`.

* Try to login using a new username in the "mail" login form. -> gets the message "Wrong username/password".
* Navigate to the "login" login form and log in using "username@mydomain",  -> gets logged in successfully.
* log out, clear cookies, and then try to log in again using the "mail" form, I am now able to successfully login.
* Go to the admin interface, navigate to the "Users" tab and delete the newly created user
* Try to login using the "mail" login form again, -> gets the message "Wrong username/password".

# Version

Running on FreeBSD with lighttpd
Afterlogic WebMail Lite PHP `8.3.7-build-a3`

**Comment by afterlogic-support** [comment]
Can you please confirm whether you have "Use full email address as login" option checked for the mail server you have added? Thank you.

**Comment by afterlogic-support** [comment]
Also, please check if there are any errors in the debug log when new user gets created. Make sure to set **LogStackTrace** to **true** in `data/settings/config.json` file.

**Comment by pbsds** [comment]
Thanks for the quick response, I've made some logs:

Here the "Use full email address as login" is unchecked, and I attempt to log in as a new user in the "mail" form: [log](https://gist.github.com/pbsds/41a05c9a5a575b3e59c26018a7f5d5a9)

Here is a successfull login attempt using the "login" form of a new user: [log](https://gist.github.com/pbsds/f1c8347359a5628f908c603a5f4c496a)

Here is a successfull login attempt using the "mail" form with an existing user: [log](https://gist.github.com/pbsds/0f87388b7cfba539838e75bcab0ede46)

Now I check the "Use full email address as login" option and delete my user. When I attempt to log in using the "mail" form I get `The username or password you entered is incorrect. (TAG1 NO (AUTHENTICATIONFAILED) Authentication failed.)` after a short wait: [log](https://gist.github.com/pbsds/3c94d1f5bd854344ce15c5ebab606980)

I am also now unable to log in using the "login" form with my new user: [log](https://gist.github.com/pbsds/f60ddcbaeb29f191aa102cbf2d0a194f)
*(perhaps due to "Use full email address as login" being checked?)*

**Comment by afterlogic-support** [comment]
Thank you, developers will take a look. Will let you know once there's a response.

**Comment by afterlogic-support** [comment]
Please try modifying **modules/MailLoginFormWebclient/Module.php** file, line **~58**:

```php
$aGetMailServerResult = \Aurora\System\Api::getModule('Mail')->GetMailServerByDomain(strtolower($sDomain), /*AllowWildcardDomain*/true);
```

as follows:

```php
$aGetMailServerResult = \Aurora\System\Api::GetModuleDecorator('Mail')->GetMailServerByDomain(strtolower($sDomain), /*AllowWildcardDomain*/true);
```

and let us know if this helps. If not, we'll need the updated logs. Thank you.

--
Regards,
Igor, Afterlogic Support

**Comment by pbsds** [comment]
### "Use full email address as login" is unchecked:

 * failed login as new user using "mail" form: [log](https://gist.github.com/pbsds/c8c699c20101f841c7f246c9fa8af3ed) \*
 * successful login as new user using "login" form: [log](https://gist.github.com/pbsds/29a1643c5637233ea3a1b659895f0e0e)
 * successful login as existing user using "mail" form: [log](https://gist.github.com/pbsds/3bd50627591db9f93c1c27beed614675)

### "Use full email address as login" is checked:

 * failed login as new user using "mail" form: [log](https://gist.github.com/pbsds/f564559f4a389238bdbc9bfb7d3692f7) \*
 * failed login as new user using "login" form: [log](https://gist.github.com/pbsds/2a121ddc89fb694440073f1d11da0c94) \*

The cases with \* appended have my password replaced with 'hunter2'

**Comment by afterlogic-support** [comment]
OK thank you. Would it be possible to provide our developers with admin access to your installation? We're also going to need a test account the issue can be reproduced with.
Please provide the access details [via HelpDesk](https://s.afterlogic.com/helpdesk). Thank you.

**Comment by afterlogic-support** [comment]
Follow-up: we were finally able to reproduce the issue on our installation. Will get back to you once there are news.

**Comment by afterlogic-support** [comment]
Please replace the following code in `modules/MailLoginFormWebclient/Module.php` file (line **~65**) :

```php
if ($oServer->UseFullEmailAddressAsLogin)
	{
		$sIncomingLogin = $sEmail;
		$bAutocreateMailAccountOnNewUserFirstLogin = \Aurora\Modules\Mail\Module::Decorator()->getConfig('AutocreateMailAccountOnNewUserFirstLogin', false);
	}
	else
	{
		$sIncomingLogin = $sLogin;
		$bAutocreateMailAccountOnNewUserFirstLogin = false;
	}
```

with:

```php
$bAutocreateMailAccountOnNewUserFirstLogin = \Aurora\Modules\Mail\Module::Decorator()->getConfig('AutocreateMailAccountOnNewUserFirstLogin', false);
$sIncomingLogin = $oServer->UseFullEmailAddressAsLogin ? $sEmail : $sLogin;
```

And let us know if this helps you. Thanks!

**Comment by afterlogic-support** [comment]
Also, we've just uploaded version 8.3.9 containing this correction and other improvements
https://afterlogic.org/download/webmail-lite-php

**Comment by pbsds** [comment]
Thanks for the help and sorry for my late reply.
This fixed it
