### ISSUE TITLE
Security improvements by introducing Content Security Policy

### ISSUE THREAD

**Issue by erikhubers** [afterlogic/webmail-lite-8#48]
Hey there,

I noticed no CSP headers defined in Afterlogic WebMail Lite/Pro. Maybe it's a nice to provide some for additional security. I've also run the demo page through [securityheaders.com](https://securityheaders.com/?q=https%3A%2F%2Fwebmail.afterlogic.com%2F&hide=on&followRedirects=on), the score (D) isn't really top notch.

**Comment by afterlogic-support** [comment]
Thank you, I've notified the developers on this.

**Comment by afterlogic-support** [comment]
The feature is implemented in Afterlogic WebMail 8.5.1:
https://afterlogic.com/docs/webmail-pro-8/security/content-security-policy
