### ISSUE TITLE
Right mouse button action

### ISSUE THREAD

**Issue by flionet89** [afterlogic/webmail-lite-8#49]
Can you make the menu appear when you click the right mouse button.
Menu when you click on the message:
Forward
Mark as
Spamming
Move
Delete
Create Filter

Menu when you click on a folder:
Clear
Squeeze
Set password

Is it possible?

**Comment by afterlogic-support** [comment]
Well yes, it's allowed to modify the source code, so you can implement the features you require.

If you'd like to submit a feature request, that can be done at https://afterlogic.uservoice.com/

If you'd like to request this as a custom development, please send us a message at https://s.afterlogic.com/helpdesk/
