### ISSUE TITLE
empty  - PHP Fatal error: Can't use function return value in write context

### ISSUE THREAD

**Issue by afonsoft** [afterlogic/webmail-lite-8#5]
PHP Fatal error: Can't use function return value in write context in E:\Inetpub\vhosts\afonsoft.com.br\files.afonsoft.com.br\system\Module\Manager.php on line 90

Note:
Prior to PHP 5.5, empty() only supports variables; anything else will result in a parse error. In other words, the following will not work: empty(trim($name)). Instead, use trim($name) == false.

**Comment by afonsoft** [comment]
phpinfo

https://nuvem32w.hoteldaweb.com.br:8443/smb/web/php-info/id/1805

**Comment by afterlogic-support** [comment]
As mentioned in Aurora Files tracker, the issue has been corrected and the updated version will be released in a few days: https://github.com/afterlogic/aurora-files/issues/2
