### ISSUE TITLE
Issue exactly the same like "Auroa not autoloadble #41"

### ISSUE THREAD

**Issue by conductor111** [afterlogic/webmail-lite-8#50]
php composer.phar run pre-config

    [ -d data ] || mkdir data
    Class Aurora\Installer is not autoloadable, can not call pre-config script

Php ver is 7. The behavior is identical for both git ver and latest.zip. Composer is the latest ver.  (They have been downloaded half an hour ago) .

**Comment by afterlogic-support** [comment]
Can you confirm you've run the following command prior to pre-config:

`php composer.phar install`

and is there `system` directory in root of your installation?

**Comment by conductor111** [comment]
Oh, yes, it was my mistake. Sorry.
