### ISSUE TITLE
Signature image being cut off at the bottom.

### ISSUE THREAD

**Issue by oktayaa** [afterlogic/webmail-lite-8#52]
This is actually two issues in one. When we add a banner image at the bottom of the signature, the gui text edit box initially displays it properly. Howevever when you refresh the browser and come to the signature page again, the banner is not displayed anymore. However it must still be there because the outgoing emails do have the banner. The problem there is the bottom portion of the banner is cut off and missing. When I open the image by itself in a browser it's still cut off so it's not a display issue but the image is actually being served that way. Any ideas? (I upgraded to the latest version to see if it would fix the issue but it didn't).

**Comment by afterlogic-support** [comment]
Does that happen with an image of any size (meaning bytes, not pixels here)? If you try with an image of 15-20Kb size, for example, do you encounter the same problem?

**Comment by oktayaa** [comment]
Will check and report back. Thanks.

**Comment by oktayaa** [comment]
The issue is same regardless of file size as far as we can tell.

**Comment by afterlogic-support** [comment]
To let us help you on this, please open a ticket in [our HelpDesk](https://s.afterlogic.com/helpdesk/) and provide a test account the issue can be reproduced with (i.e. the signature already contains a problematic image). Thanks.

**Comment by oktayaa** [comment]
I didn't have a chance to make a test account but I saw an error related to data loss in the logs. Might this be related to this issue?

[Wed Nov 27 07:44:11.664798 2019] [proxy_fcgi:error] [pid 21500] [client 95.70.200.107:28611] 
AH01071: Got error 'PHP message: PHP Warning:  fread(): \\MailSo\\Base\\StreamWrappers\\SubStreams::stream_read - read 35 bytes more data than requested 
(8227 read, 8192 max) - excess data will be lost in /opt/afterlogic-8.2.3/vendor/afterlogic/mailso/lib/MailSo/Base/Utils.php on line 1807\n', referer: https://ergil.com/mail/

**Comment by afterlogic-support** [comment]
No, that doesn't look critical.
By the way, it looks like you're running quite an outdated version 8.2.3 released over a year ago.
Make sure to switch to the latest version and see if the issue is reproduced there.

**Comment by oktayaa** [comment]
Hi. I actually just deleted my comment before reading yours. I noticed the same thing about the release version. It looks like I wasn't able to complete my last update and the config symlink is still pointing to the old version. I will upgrade to the latest version properly then test again. I am closing this until I do that and have a chance to check. Thanks.

**Comment by bzenky** [comment]
Hello there, I´m having the first part of the problem explained above, I upload a image in the signature section, at first it works, but when logout and login again, the signature disapears. I have the 8.5.2 version.

**Comment by afterlogic-support** [comment]
Try clearing browser cache and see if the signature shows correctly after logging into WebMail again.

Does it help?

**Comment by bzenky** [comment]
No, the problem continues, and in the signature, it disapears.

**Comment by afterlogic-support** [comment]
Understood, we'll need a test account the issue can be reproduced with, and adminpanel credentials. Please send the details [via HelpDesk](https://s.afterlogic.com/helpdesk). Thank you.

**Comment by afterlogic-support** [comment]
Upon the investigation, developers confirmed that the problem is caused by exceeding 64Kb limit in database text fields. Images in signature are presented in base64 encoding, signature is stored in database, so if the image is too big MySQL cuts it. You can change "value" field type in "au_eav_attributes_text" table from TEXT to LONGTEXT, then the image will be kept in signature:

```sql
ALTER TABLE `au_eav_attributes_text` CHANGE `value` `value` MEDIUMTEXT;
```

**Comment by oktayaa** [comment]
Will this be in the next release?

**Comment by afterlogic-support** [comment]
Can't tell at the moment, but the developers will consider including such a change in the future releases.

**Comment by bzenky** [comment]
> 
> 
> Upon the investigation, developers confirmed that the problem is caused by exceeding 64Kb limit in database text fields. Images in signature are presented in base64 encoding, signature is stored in database, so if the image is too big MySQL cuts it. You can change "value" field type in "au_eav_attributes_text" table from TEXT to LONGTEXT, then the image will be kept in signature:
> 
> ```sql
> ALTER TABLE `au_eav_attributes_text` CHANGE `value` `value` MEDIUMTEXT;
> ```

Thanks!
