### ISSUE TITLE
installing Version 8 Lite on plesk error

### ISSUE THREAD

**Issue by worldofmadness** [afterlogic/webmail-lite-8#54]
hi every-time i try and install the version 8 lite version on plesk i get the following error.

![chrome_cJiakySLh5](https://user-images.githubusercontent.com/17691564/69144401-24c4d000-0ac3-11ea-9638-96b9786d5a40.png)

any ideas how to get it on plesk?

**Comment by afterlogic-support** [comment]
It looks like you're trying to install a regular package but we do have a Plesk package available for WebMail Lite:
https://afterlogic.org/download/webmail-lite-php
On that page, select "Plesk Panel application" and proceed with download and install.
