### ISSUE TITLE
I Can not Login User Mail

### ISSUE THREAD

**Issue by onurozden** [afterlogic/webmail-lite-8#55]
Everything works smoothly except for one thing. I'm creating a new mail user. However, when I try to log in to the mail user from the following URL, I get the login failed error. I've tried dozens of different combinations. Also, see log files and a screenshot.

user log file: https://paste.ubuntu.com/p/rbKykxpWYD/
admin log file: https://paste.ubuntu.com/p/MzKG9RZ5nX/
Screenshot: https://i.hizliresim.com/NLRb3L.png

**Comment by afterlogic-support** [comment]
According to the logs, imap.bahcelievlerveteriner.org hostname does not exist, make sure to supply correct hostname of your IMAP server.

Also, normally there should be no need to create users in admin interface. As long as mail account exists on mail server, and you've specified server details correctly, users should be able to log into their accounts right away.

**Comment by afterlogic-support** [comment]
One more point worth pointing out: seems you're attempting to use SSL on a standard port, usually you need to supply a dedicated SSL port for that - 993 for IMAP, 465 for SMTP.
