### ISSUE TITLE
Attached images not being displayed under some conditions 

### ISSUE THREAD

**Issue by prsliwa** [afterlogic/webmail-lite-8#60]
Hi, 

In some emails images are not displayed properly, seems like src tag is missing:

![obraz](https://user-images.githubusercontent.com/11444225/77237404-3bda1280-6bc8-11ea-9dc7-c9be90317017.png)
Image suppose to be in selected section, on roundcube for example it's being displayed properly:
![obraz](https://user-images.githubusercontent.com/11444225/77237443-91aeba80-6bc8-11ea-85c2-a788e214a1d3.png)

It seems like tags are generated however they are missing src:
![obraz](https://user-images.githubusercontent.com/11444225/77237473-c753a380-6bc8-11ea-8827-77aa9032f418.png)

I have emailed myslef some test mails with inline pictures but I could not reproduce it however from time to time emails shows this specific way.
How could I check it more in deep?

Regards
Przemek

**Comment by afterlogic-support** [comment]
To let us check this, please provide us with a sample email message using [our HelpDesk](https://s.afterlogic.com/helpdesk). Thanks.

**Comment by afterlogic-support** [comment]
Thread closed due to inactivity. Feel free to reopen should the issue occur with the latest version.
