### ISSUE TITLE
Cookies are disabled in the browser. Please enable them for this web site and reload the page.

### ISSUE THREAD

**Issue by ytteroy** [afterlogic/webmail-lite-8#61]
The popup "Cookies are disabled in the browser. Please enable them for this web site and reload the page." keeps displaying, even though I know for a fact that cookies are enabled on my browser. 

This problem occurs only for a few users. For example, I can access from desktop browser, but from Android Chrome - this error occurs. Do you have any additional information to fix this error? I'm using Cloudflare.

**Comment by afterlogic-support** [comment]
Try disabling CSRF protection per:
https://afterlogic.com/docs/webmail-lite-8/security/csrf-protection

Does it help?

**Comment by afterlogic-support** [comment]
Thread closed due to inactivity. Feel free to reopen should the issue occur with the latest version.
