### ISSUE TITLE
reCaptcha

### ISSUE THREAD

**Issue by glararan** [afterlogic/webmail-lite-8#63]
Hi,

I just updated webmail to latest version, added google recaptcha v2 - checkbox type. Getting following error at login: reCAPTCHA unknown error.

What could be wrong?

**Comment by afterlogic-support** [comment]
We've noticed that issue as well, seems like something has changed on Google API side. Developers suggest adjusting `modules/RecaptchaWebclientPlugin/Module.php` file and replacing both the occurences of:

```
$oRecaptcha = new \ReCaptcha\ReCaptcha($sPrivateKey, new \ReCaptcha\RequestMethod\SocketPost());
```

with:

```
$oRecaptcha = new \ReCaptcha\ReCaptcha($sPrivateKey, new \ReCaptcha\RequestMethod\CurlPost());
```

or, if that one doesn't do the trick, with:

```
$oRecaptcha = new \ReCaptcha\ReCaptcha($sPrivateKey);
```
Let us know if either of those worked for you. Thanks.

**Comment by glararan** [comment]
@afterlogic-support thanks for supp.

Second one did the trick. Thanks
