### ISSUE TITLE
cpanel password change issue

### ISSUE THREAD

**Issue by BreeOge** [afterlogic/webmail-lite-8#64]
Cpanel always uses lowercase when logging in.  However for some reason its using the Email from the database as the account login, and it could possibly have uppercase letters.  The Cpanel account needs to covert the email to all lowercase before trying to log in

**Comment by afterlogic-support** [comment]
Are you referring to logging in itself, or specifically the password change?

**Comment by BreeOge** [comment]
Specifically the password change.  I can log into the same account using any case.  But when you go to change the password, it sends the login info to change the password exactly how the email was entered on making the account.  Cpanel will only allow you to use lowercase.  really 2 ways I can think of fixing this, 1. When you login to an account for the first time into cpanel, it creates the login ect.  This could be forced lowercase here, and it will solve all problems.   Or 2. It needs to make sure its sending all lowercase when doing a cpanel password change.  I have not tried the other features such as adding forwards ect. but I would suspect they will be subject to the same issue.

**Comment by afterlogic-support** [comment]
OK thank you for the clarification, I've asked the developers to look into this.

**Comment by afterlogic-support** [comment]
Thread closed due to inactivity. Feel free to reopen should the issue occur with the latest version.
