### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by Moortingale** [afterlogic/webmail-lite-8#66]
After installation from softaculous, opening the website it gives this error:

Parse error: syntax error, unexpected '[', expecting ')' in /home/petik637/public_html/mailaja.com/system/Application.php on line 36

**Comment by sash04ek** [comment]
What version of PHP are you using?

**Comment by Moortingale** [comment]
PHP 7.3. which version should I be using?

**Comment by afterlogic-support** [comment]
The error itself suggests a **much** older PHP version is used, 5.3 or older. We're not familiar with softaculous, but you can place a PHP file containing the following code:

<?php phpinfo();

into webmail directory and open it from web browser, to check what PHP version is used there. Or, contact your hosting provider regarding PHP version used in a product installed via softaculous.

**Comment by afterlogic-support** [comment]
The error itself suggests a **much** older PHP version is used, 5.3 or older. We're not familiar with softaculous, but you can place a PHP file containing the following code:

![phpinfo](https://user-images.githubusercontent.com/16918936/82191047-a07cc980-98fa-11ea-9600-58eb4b7448a9.png)

into webmail directory and open it from web browser, to check what PHP version is used there. Or, contact your hosting provider regarding PHP version used in a product installed via softaculous.
