### ISSUE TITLE
TLS Port Hardcoded

### ISSUE THREAD

**Issue by SniperFodder** [afterlogic/webmail-lite-8#68]
I recently removed port 465 from my port listing as it's not an officially designated port for TLS Communications. When I tried to send an email, I of course got an error that that the webmail client could not send a message. I reviewed the settings and discovered I hadn't changed the port listed for SMTP in the settings in the backend. I updated it to 587, and tried testing again. Issue persisted, and when looking at the logs, I can see it's still trying to reach out to 465 instead of the port I have in my settings. I've tried rebooting the Webmail server, and my mail server, so it's definitely something that is hard coded.

Server Version: Apache/2.4.41 (Win64) OpenSSL/1.1.1e PHP/7.4.4
Server MPM: WinNT
Apache Lounge VS16 Server built: Aug 9 2019 16:46:32
AfterLogic Webmail Lite: 7.6.10

**Comment by afterlogic-support** [comment]
Sorry that version is extremely old (released over 5 years ago) and cannot be supported. Make sure you're using the latest version 8 of the product.
