### ISSUE TITLE
get messages error

### ISSUE THREAD

**Issue by maltboy** [afterlogic/webmail-lite-8#69]
Hi,afterlogic-support
Use Obtains message list for specified account and folder.
I receive the following error.
Unknown error. (TAG6 BAD Invalid UID command: 'SORT' Command should be ' UID |||').
I tried to use UID sorting, the result still prompts the error, please help me, thanks!

**Comment by afterlogic-support** [comment]
So are you saying the issue only occurs for a particular account? That looks like an issue with mailserver, can you post the [debug logs](https://afterlogic.com/docs/webmail-lite-8/troubleshooting/debug-logging-as-main-troubleshooting-measure) here? You can also send us the account details [via HelpDesk](https://s.afterlogic.com/helpdesk/) so we can check what's going on there; and though WebMail Lite doesn't come with guaranteed free support from Afterlogic, we would still like to take a look.

**Comment by maltboy** [comment]
![1](https://user-images.githubusercontent.com/57748904/85349991-7be7c300-b532-11ea-98bb-fd4a53037ab9.png)
![2](https://user-images.githubusercontent.com/57748904/85350012-886c1b80-b532-11ea-9258-270503114378.png)
![3](https://user-images.githubusercontent.com/57748904/85350450-c0279300-b533-11ea-841f-4c7ab4581874.png)

This is a screenshot of the run.I did not find relevant information on the log.
The problem appears in this type of mailbox, and other functions are normal. When it is installed in the list of messages, it prompts that the sort field is wrong.

**Comment by afterlogic-support** [comment]
I'm afraid that's not enough information to provide any insight. We'll need either logs or the account credentials. Thanks.

**Comment by maltboy** [comment]
This is a test mailbox.
mike@sinobasemetal.com 
password：aaa@2019
You can use it for testing. 
thanks!

**Comment by afterlogic-support** [comment]
Thank you. We've removed the credentials from the post for privacy reasons.
Can you please also provide IMAP host you're connecting to? Thanks.

**Comment by maltboy** [comment]
This is the configuration information.  Thank you.

imap：s18.cn4e.com     prot：993    SSL

smap:  s18.cn4e.com     prot：465    SSL

**Comment by afterlogic-support** [comment]
Thanks. It looks like IMAP server you use advertises SORT extension but doesn't provide correct support for it. To work around that, locate the following section in `data/settings/modules/Mail.config.json` configuration file:

```json
"MessagesSortBy": [
	{
		"Allow": true,
		"List": [],
		"DefaultSortBy": "arrival",
		"DefaultSortOrder": "desc"
	},
	"array"
],
```

and set "Allow" to **false** there.

Hope this helps.

**Comment by maltboy** [comment]
Thank you. If it is changed to false, does it mean that the sorting function is disabled?
Will it affect my normal sort function.

**Comment by afterlogic-support** [comment]
By default, WebMail only sorts mail messages by date in reverse order. It's possible to configure [message sorting](https://afterlogic.com/docs/webmail-lite-8/configuring-webmail/messages-sorting) but that requires IMAP SORT to work properly - which apparently isn't the case, so turning sorting off seems to be the only viable approach. If you wish to use sorting on that server, consider contacting email service provider in this regard.
