### ISSUE TITLE
mobile version not working

### ISSUE THREAD

**Issue by wociscz** [afterlogic/webmail-lite-8#7]
Hi, there are missing styles-mobile.css files in themes directories - are they missing on purpose - i mean are they available only in licensed version or so?

When switching to mobile version on cell phone - it ends up with blank page.

**Comment by afterlogic-support** [comment]
Hello,
Thank you for the report. Mobile version is actually is a Pro feature, switching to it shouldn't be offered in Lite, we'll have it fixed in the next update.

**Comment by afterlogic-support** [comment]
Also, if you may be interested in checking out the Pro Beta:
https://afterlogic.com/webmail-pro-8

**Comment by joegrantstn** [comment]
Adding a note here in case anyone else has this issue...
- My server is using Afterlogic Webmail Pro 8
- when viewed on mobile, users get a sign in form and can sign in, but it sends them to a blank page.

## Solution
In the default settings, there is a configuration file that has the mobile web client disabled.
`data/settings/modules/SettingsMobileWebclient.config.json`

Setting Disabled to "false" in this file fixed the blank screen issue for me.

**Comment by afterlogic-support** [comment]
**joegrantstn**, thank you, developers will look into this.

**Comment by NRSHAOWN** [comment]
There is No Signup form for Mobile Version? going to domain.com/#signup from mobile only sign in form is coming. (Pro 9 Using)
