### ISSUE TITLE
Searching emails - issue when orthography

### ISSUE THREAD

**Issue by MrShippeR** [afterlogic/webmail-lite-8#71]
Hello,
i think problem is about formating search sentence to mail hosting. There is probably missing support of UTF-8. Could someone who understant problematic fill the gap and edit code to support UTF-8, please?

I get error:
`Neznámá chyba. (TAG6 NO SORT: mtd: internal error: SEARCH Syntax error (Bad token)`

when I try to search any word with [czech orthography](https://en.wikipedia.org/wiki/Czech_orthography) like "česko" = czech  
![Snímek z 2020-11-02 22-24-37](https://user-images.githubusercontent.com/12204070/97920810-4c578b80-1d5a-11eb-8dea-4dc9c76a8159.png)

**Comment by afterlogic-support** [comment]
This might actually be caused by UTF8 support missing for search on mail server side. To look into this further, we'd need [debug logs](https://afterlogic.com/docs/webmail-lite-8/troubleshooting/debug-logging-as-main-troubleshooting-measure) recorded when performing IMAP search.

**Comment by MrShippeR** [comment]
Debug log in attachment for search word "česko". Thank you for your helping.
[log-2020-11-03.txt](https://github.com/afterlogic/webmail-lite-8/files/5479663/log-2020-11-03.txt)

**Comment by MrShippeR** [comment]
Email provider is [seznam.cz](https://www.seznam.cz/). I'm using domain email.cz there, but domain shouldn't matter.
Setting for email client is [here](https://napoveda.seznam.cz/cz/email/imap-pop3-smtp/). For case of duplication my situation.

**Comment by afterlogic-support** [comment]
Indeed, it looks like this particular mail server doesn't support UTF8 search, you may wish to contact their support in this regard.
On our own server, using [WebMail Lite live demo](https://lite.afterlogic.com/), such a search is performed just fine.

**Comment by MrShippeR** [comment]
Seems they are using RFC 2822 or RFC 5322

Please, where can I find line of used formating and replace UTF-8 by one of these? In which file in my copy of program?

**Comment by afterlogic-support** [comment]
**getMessagesInfo** function in `modules/Mail/Managers/Main/Manager.php` file would be a starting point.

By the way, you can try replacing the following line therre:

```php
bUseSortIfSupported = $oImapClient->IsSupported('SORT'); 
```

with:

```php
bUseSortIfSupported = false; 
```

There's a chance this will help, if mail server can't handle SORT but can do simple SEARCH.
