### ISSUE TITLE
Pre-Install Features Question

### ISSUE THREAD

**Issue by SolarSistim** [afterlogic/webmail-lite-8#72]
Hi Afterlogic,

I just set up After Logic's Aurora Files yesterday, I love it and I'm moving on to installing Webmail Lite PHP. I've browsed the documentation and didn't find an answer to a couple of questions, I'm hoping that you can help me before I proceed.

- Can I add multiple email accounts to WebMail Lite, in the same way I can add multiple email accounts in Outlook? Example: I want to add a Gmail address, a Yahoo address and a corporate email address.

- When this is running on my server, will I have to forward email ports to the application? Example: post 587, 25, and/or 465?

I'm looking forward to having a uniformed communication set-up on my server using all Afterlogic applications. Thanks in advance!

**Comment by afterlogic-support** [comment]
> Can I add multiple email accounts to WebMail Lite, in the same way I can add multiple email accounts in Outlook? Example: I want to add a Gmail address, a Yahoo address and a corporate email address.

That's only available in the [Pro version](https://afterlogic.com/webmail-client).

> When this is running on my server, will I have to forward email ports to the application? Example: post 587, 25, and/or 465?

There should be no need for that, assuming those ports are actually open and can be used by a web application.
