### ISSUE TITLE
PHP8 support

### ISSUE THREAD

**Issue by anomality** [afterlogic/webmail-lite-8#73]
According to PHP 8 is in production state now, the code of webmail-lite should be updated.
I'm getting:

`Parse error: syntax error, unexpected token "\" in /var/www/webmail/htdocs/system/Module/Manager.php on line 362`

Go on with your product, because it's really one of the best! :+1:

**Comment by afterlogic-support** [comment]
Hello,

A fix for that is already implemented [in the respective repository](https://github.com/afterlogic/aurora-framework/blob/master/Module/Manager.php) and will be included in the next release of the product.

In fact it was a typo, the code in question should look like this:
```php
$sTemplateSource = \str_replace('{%INCLUDE-START/'.$aItem[0].'/INCLUDE-END%}',
	$sTemplateHtml.'{%INCLUDE-START/'.$aItem[0].'/INCLUDE-END%}', $sTemplateSource);
````

Thanks.
