### ISSUE TITLE
Backend error when use search

### ISSUE THREAD

**Issue by rsavchak** [afterlogic/webmail-lite-8#74]
Hello, when i use serch, i get this error message: 
"Unknown error. (TAG6 NO (UNAVAILABLE) UID SEARCH Backend error. sc=oUKM15T7x8c1_041330_4-22bc986af89b)".
The mail server is yandex

**Comment by afterlogic-support** [comment]
Can you post the logs reflecting search command sent to IMAP server?
https://afterlogic.com/docs/webmail-lite-8/troubleshooting/debug-logging-as-main-troubleshooting-measure

**Comment by afterlogic-support** [comment]
Quick Google check shows there's an odd issue with Yandex IMAP:
https://stackoverflow.com/questions/59325496/error-uid-search-failure-due-to-backend-error-imap-uid-node-js-imap-yandex

**Comment by afterlogic-support** [comment]
Thread closed due to inactivity. Feel free to reopen should the issue occur with the latest version.
