### ISSUE TITLE
get 504 timeout

### ISSUE THREAD

**Issue by hitechbeijing** [afterlogic/webmail-lite-8#75]
if install pdo with mysqlnd, nginx get 504 Gateway Time-out error. I have try both php 7.2 and php 7.4.

**Comment by afterlogic-support** [comment]
Is there anything relevant in nginx or PHP error logs? Also, is the issue specific to our webmail, and scripts like this work fine?

```php
<?php phpinfo();
```

**Comment by hitechbeijing** [comment]
am not find any php error, and the phpinfo() works fine.

发自我的iPhone

**Comment by afterlogic-support** [comment]
Understood. Still, we would need an error log record to assist any further on this.

**Comment by afterlogic-support** [comment]
Thread closed due to inactivity. Feel free to reopen should the issue occur with the latest version.
