### ISSUE TITLE
Adaptive mobile UI 

### ISSUE THREAD

**Issue by IgorKhomenko** [afterlogic/webmail-lite-8#79]
Hi there, 

is there any plans to add adaptive mobile UI ? Or is there any other repo which can be used at mobile?

Thanks

**Comment by afterlogic-support** [comment]
WebMail Pro offers mobile-friendly interface:
https://afterlogic.com/docs/webmail-pro-8/frequently-asked-questions/mobile-version
Note that, unlike WebMail Lite, it's a commercial product and requires purchasing a license.
The repository is found at:
https://github.com/afterlogic/webmail-pro-8
Hope this helps.
