### ISSUE TITLE
How to run an app in a 'Calendar' mode only

### ISSUE THREAD

**Issue by IgorKhomenko** [afterlogic/webmail-lite-8#81]
Hi everyone, 

Is there a way to disable Mail module and run an app in a 'Calendar' mode only? either with lite or pro version 

Thnaks in advance

**Comment by afterlogic-support** [comment]
Calendar is a Pro feature, it's not available in WebMail Lite.

In WebMail Pro, you can disable all the modules except Calendar, by setting "Disabled" to **true** in the following files under `data/settings/modules` directory: MailWebclient.config.json, FilesWebclient.config.json, ContactsWebclient.config.json, Tasks.config.json.

Note that the authentication will still be done via IMAP so an account has to exist on mail server.
