### ISSUE TITLE
"Mail servers settings" become empty after upgrade

### ISSUE THREAD

**Issue by GaneshKandu** [afterlogic/webmail-lite-8#82]
We are trying to upgrade WebMail Lite 8.8.3 to WebMail Lite 9.0.0  but when we update "Mail servers settings" become empty after upgrade,
"eav_attributes_string" table still contain Mail servers settings in it but "mail_servers" table is empty,

**Comment by afterlogic-support** [comment]
Make sure you run the migration script as showh here:
https://afterlogic.com/docs/webmail-lite/installation/upgrading-instructions#upgrading-from-v8

**Comment by GaneshKandu** [comment]
> Make sure you run the migration script as showh here:

I don't have access to make commands, is there any way to do this with from browser?

**Comment by afterlogic-support** [comment]
Not at the moment, we're going to provide web-based migration script in the next update.
Meantime, you can download the installation (both the data directory and the database) and run the migration locally, then upload the results back to the server.
