### ISSUE TITLE
Can i use it with multiple IMAP accounts, not jus as identities / sub-account - similar to a non-web IMAP-Client OR Outlook365?

### ISSUE THREAD

**Issue by jayjupdhig** [afterlogic/webmail-lite-8#86]
- Can i use it with multiple IMAP accounts, not jus as identities / sub-account - similar to a non-web IMAP-Client OR Outlook365?

- If yes: What PHP version is necessary?

Thanks in advance for your feedback.

With kind regards from Switzerland,
Jan

**Comment by jayjupdhig** [comment]
What's the difference between "webmail-lite-8" and "webmail-lite" - https://github.com/afterlogic/webmail-lite-8 vs. https://github.com/afterlogic/webmail-lite ?

**Comment by jayjupdhig** [comment]
-> https://github.com/afterlogic/webmail-lite/issues/102

**Comment by afterlogic-support** [comment]
https://github.com/afterlogic/webmail-lite - legacy version 7 of WebMail Lite
https://github.com/afterlogic/webmail-lite-8 - current version, 9.3.1 at the moment.

If you wish to use premium features such as multiple accounts support, you're looking for the commercial WebMail Pro:
https://afterlogic.com/webmail-client

**NB:** This tracker is for reporting issues. Please use the community forum to ask general questions about the product:
https://s.afterlogic.com/forum/forum_topics.asp?FID=28

**Comment by kosuodhmwa** [comment]
thank you very much!! :-)
