### ISSUE TITLE
Maintained ?

### ISSUE THREAD

**Issue by BirdInFire** [afterlogic/webmail-lite-8#87]
I have to ask, since it's not updated (in release zone) since 2020, does this webmail actually maintained ?

**Comment by afterlogic-support** [comment]
The product is actively maintained indeed, you can get the latest built package from [WebMail Lite product page](https://afterlogic.org/webmail-lite). Building a new package doesn't require updating root repository, aside from minor changes like VERSION file updates - but we do add new tags in other repositories used ([this one](https://github.com/afterlogic/aurora-framework/tags), for example).
