### ISSUE TITLE
Missing arrow icon (Show details/Hide details) in the div.header_row

### ISSUE THREAD

**Issue by mdesign83** [afterlogic/webmail-lite-8#92]
I miss the small arrow icon from div.header_row.
If I add the "MessageDetailsVisible":"1" entry to localStorage, it is working nicely, but it would be great if the arrow would be visible.
I couldn't find the config for that.
It's missing on https://lite.afterlogic.com site also.

Best regards,
Karoly

**Comment by afterlogic-support** [comment]
I've just checked this at https://lite.afterlogic.com/ using a new browser installation I've never accessed it with, and the arrow is perfectly in place:

![show-details-arrow](https://user-images.githubusercontent.com/16918936/198563359-0fc15a1c-4ae8-435e-a837-7a23aaf6bff8.png)

What browser/OS are you using? And, does the issue occur in another browser too?

**Comment by mdesign83** [comment]
I came from version 7, and 🤦‍♂️ I haven't noticed its new place...
Thanks!
