### ISSUE TITLE
back from "logging in programmatically"

### ISSUE THREAD

**Issue by touringo** [afterlogic/webmail-lite-8#94]
Hello, after successfully entering into webmail account programatically, when user clicks on exit button he remains logged in into webmail. How to make user really exit from webmail in order to transfer him elsewhere?
Another question: is there a way to hide folders "special", "spam", "drafts" ?

**Comment by afterlogic-support** [comment]
> Hello, after successfully entering into webmail account programatically, when user clicks on exit button he remains logged in into webmail. How to make user really exit from webmail in order to transfer him elsewhere?

That probably means you didn't set set cookie path as described at:
https://afterlogic.com/docs/webmail-lite/developers-guide/logging-in-programmatically
I'm referring to the following section:

> Also note that "/" stands for cookie path which should point to the installation folder. If you have WebMail Lite set up in subfolder of the domain, e.g. yourdomain.com/webmail then you need to adjust the path accordingly:
```php
setcookie('AuthToken', $sAuthToken, time()+3600, "/webmail/");
```

> Another question: is there a way to hide folders "special", "spam", "drafts" ?

Using "Setup special folders" tool of Manage Folders screen, you can set "No usage assigned" for such a folder and then delete it. Note that turning a particular folder off will also disable functionality related to it. For example, if you unassign Trash folder, messages will be deleted permanently right away.

**NB:** This tracker is for reporting issues with the product. Community support is available at the forum:
https://s.afterlogic.com/forum/forum_topics.asp?FID=28
