### ISSUE TITLE
Feature Request: Purge Emails, Filter rules

### ISSUE THREAD

**Issue by joel72265** [afterlogic/webmail-lite-8#96]
Thank you for a wonderful application.

New Feature 1: Purge emails older than 60 days 
New Feature 2: Move emails from xxx to trash (or to folder)
New Feature 3: leave emails on server

**Comment by afterlogic-support** [comment]
> Move emails from xxx to trash (or to folder)
This is actually implemented already.

As for the other features, please feel free to post a feature request at:
https://afterlogic.uservoice.com/forums/932335-webmail-pro
